name: textbook

channels:
  - conda-forge

dependencies:
  - pip:
    - bs4
    - tqdm
    - numpy
    - datascience
    - pyyaml
    - nbformat
    - nbclean
    - numpy
    - pandas
    - scipy
    - folium==0.2.1
    - matplotlib
    - datascience
    - ipywidgets>=7.0.0
    - bqplot
    - nbinteract==0.0.12
